version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: rentfax-backend
    ports:
      - "5050:5050"
    env_file:
      - ./backend/.env
    networks:
      - rentfax-net
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend-react
    container_name: rentfax-frontend
    ports:
      - "5173:80"  # Browser: http://localhost:5173
    networks:
      - rentfax-net
    restart: unless-stopped

networks:
  rentfax-net:
    driver: bridge
