import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | RentFAX",
  description:
    "Learn how RentFAX collects, uses, and protects renter data, identity verification information, incident reports, and risk insights.",
};

export default function PrivacyPolicyPage() {
  return (
    <main className="min-h-screen bg-white text-gray-800">
      {/* HERO */}
      <section className="py-20 px-6 bg-gradient-to-b from-slate-50 to-white border-b">
        <h1 className="text-5xl font-bold mb-4">Privacy Policy</h1>
        <p className="text-lg text-gray-600 max-w-3xl">
          Last updated: January 2025  
          <br />
          This Privacy Policy explains how RentFAX, Inc. (“RentFAX,” “we,” “our,” or “us”) collects, uses, shares, and protects personal information within the RentFAX platform.
        </p>
      </section>

      {/* CONTENT */}
      <section className="py-16 px-6 max-w-5xl mx-auto space-y-12">

        {/* 1 */}
        <div>
          <h2 className="text-2xl font-bold mb-3">1. Overview</h2>
          <p className="leading-relaxed">
            RentFAX provides rental intelligence services, including identity verification,
            incident reporting, fraud signal detection, renter risk scoring, and dispute
            resolution tools. This Policy applies to all users, including landlords, renters,
            agencies, companies, and partners accessing any part of the RentFAX platform or API.
          </p>
        </div>

        {/* 2 - Data We Collect */}
        <div>
          <h2 className="text-2xl font-bold mb-3">2. Information We Collect</h2>

          <h3 className="text-xl font-semibold mt-4 mb-2">A. Information You Provide</h3>
          <ul className="list-disc pl-6 space-y-2">
            <li>Identity information (name, email, phone, address)</li>
            <li>Renter-submitted documents during verification</li>
            <li>Incident reports, disputes, comments, and evidence files</li>
            <li>Landlord and company account information</li>
            <li>Billing and plan subscription details (processed via Stripe)</li>
          </ul>

          <h3 className="text-xl font-semibold mt-4 mb-2">B. Automatically Collected Information</h3>
          <ul className="list-disc pl-6 space-y-2">
            <li>IP address, browser type, device metadata</li>
            <li>Login timestamps and authentication events</li>
            <li>Search activity related to renter lookups</li>
            <li>Fraud signals generated by AI or system heuristics</li>
          </ul>

          <h3 className="text-xl font-semibold mt-4 mb-2">C. Third-Party Sources</h3>
          <p className="leading-relaxed">
            RentFAX may receive additional information through identity verification vendors,
            address validation services, a property manager, and participating rental partners.
          </p>
        </div>

        {/* 3 - How We Use Data */}
        <div>
          <h2 className="text-2xl font-bold mb-3">3. How We Use Your Information</h2>
          <ul className="list-disc pl-6 space-y-2">
            <li>Conduct identity verification and detect fraudulent submissions.</li>
            <li>Generate renter risk insights and behavioral indicators.</li>
            <li>Provide reports, timelines, and incident histories to authorized users.</li>
            <li>Support dispute resolution between renters and landlords.</li>
            <li>Improve product features, AI models, and fraud intelligence systems.</li>
            <li>Comply with legal obligations, audits, or governmental requests.</li>
          </ul>
        </div>

        {/* 4 - Legal Basis */}
        <div>
          <h2 className="text-2xl font-bold mb-3">4. Legal Basis for Processing</h2>
          <p>
            As a U.S.-based provider, RentFAX processes data under applicable U.S. privacy
            laws including FCRA-adjacent obligations, consumer dispute rights, and state-level regulations such as the California Consumer Privacy Act (CCPA/CPRA).
          </p>
        </div>

        {/* 5 - Sharing */}
        <div>
          <h2 className="text-2xl font-bold mb-3">5. How We Share Information</h2>
          <p className="mb-3">
            RentFAX only shares personal information with:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Authorized landlords, property managers, or agencies</li>
            <li>Renters involved in disputes or verification processes</li>
            <li>Service providers (identity verification, analytics, and storage vendors)</li>
            <li>Stripe for billing and payment processing</li>
            <li>Law enforcement when legally required</li>
          </ul>
        </div>

        {/* 6 - Renter Rights */}
        <div>
          <h2 className="text-2xl font-bold mb-3">6. Renter Data Rights</h2>
          <ul className="list-disc pl-6 space-y-2">
            <li>Access your RentFAX profile and reports</li>
            <li>Submit disputes and corrections</li>
            <li>Provide evidence or supporting materials</li>
            <li>Request deletion where applicable under U.S. law</li>
          </ul>
        </div>

        {/* 7 - Security */}
        <div>
          <h2 className="text-2xl font-bold mb-3">7. Data Security</h2>
          <p>
            RentFAX uses encryption, secure storage, access control, audit logging, and
            multi-layered authentication systems. No system is fully secure, and users
            accept inherent risks associated with digital services.
          </p>
        </div>

        {/* 8 - Children */}
        <div>
          <h2 className="text-2xl font-bold mb-3">8. Children’s Privacy</h2>
          <p>
            RentFAX does not knowingly collect information from individuals under 18.
          </p>
        </div>

        {/* 9 - Retention */}
        <div>
          <h2 className="text-2xl font-bold mb-3">9. Data Retention</h2>
          <p>
            RentFAX retains reports, disputes, and verification data only as long as
            necessary for platform functionality, compliance needs, or legal requirements.
          </p>
        </div>

        {/* 10 - Updates */}
        <div>
          <h2 className="text-2xl font-bold mb-3">10. Changes to this Policy</h2>
          <p>
            Updates will be posted here. Continued use of the platform constitutes acceptance.
          </p>
        </div>

        {/* Contact */}
        <div>
          <h2 className="text-2xl font-bold mb-2">Contact Us</h2>
          <p>
            privacy@rentfax.io  
            <br />
            RentFAX, Inc.
          </p>
        </div>
        <p className="text-sm text-gray-600 mt-6">
            For legally binding terms, see our{" "}
            <a href="/privacy" className="text-blue-600 font-semibold">
                Privacy Policy
            </a>
            .
        </p>
      </section>
    </main>
  );
}
