
export const INCIDENT_TYPES = {
  CAR: {
    NON_PAYMENT: "NON_PAYMENT",
    VEHICLE_DAMAGE: "VEHICLE_DAMAGE",
    UNAUTHORIZED_DRIVER: "UNAUTHORIZED_DRIVER",
    ABANDONMENT: "ABANDONMENT",
    THEFT: "THEFT",
    TOLLS_TICKETS: "TOLLS_TICKETS",
    SMOKING: "SMOKING",
    ILLEGAL_ACTIVITY: "ILLEGAL_ACTIVITY",
  },

  PROPERTY: {
    LATE_RENT: "LATE_RENT",
    DAMAGE: "DAMAGE",
    DISTURBANCE: "DISTURBANCE",
    LEASE_VIOLATION: "LEASE_VIOLATION",
    POLICE_CALLED: "POLICE_CALLED",
    UNAUTHORIZED_OCCUPANT: "UNAUTHORIZED_OCCUPANT",
  },

  EQUIPMENT: {
    DAMAGED: "DAMAGED",
    ABANDONED: "ABANDONED",
    THEFT: "THEFT",
    OVERDUE: "OVERDUE",
    MISUSE: "MISUSE",
  },

  SHORT_TERM: {
    SMOKING: "SMOKING",
    DAMAGE: "DAMAGE",
    PARTY: "PARTY",
    VIOLATION: "VIOLATION",
    UNAUTHORIZED_GUEST: "UNAUTHORIZED_GUEST",
  }
};
