
export function normalizeIncident(industry: string, type: string) {
  const map: Record<string, string> = {
    NON_PAYMENT: "FINANCIAL_RISK",
    LATE_RENT: "FINANCIAL_RISK",
    OVERDUE: "FINANCIAL_RISK",

    VEHICLE_DAMAGE: "PROPERTY_DAMAGE",
    DAMAGE: "PROPERTY_DAMAGE",
    EQUIPMENT_DAMAGE: "PROPERTY_DAMAGE",

    UNAUTHORIZED_DRIVER: "UNAUTHORIZED_ACCESS",
    UNAUTHORIZED_OCCUPANT: "UNAUTHORIZED_ACCESS",
    UNAUTHORIZED_GUEST: "UNAUTHORIZED_ACCESS",

    ABANDONMENT: "ABANDONMENT",
    THEFT: "THEFT",
    ILLEGAL_ACTIVITY: "ILLEGAL_ACTIVITY",
    PARTY: "ILLEGAL_ACTIVITY",
    POLICE_CALLED: "ILLEGAL_ACTIVITY",

    TOLLS_TICKETS: "FINANCIAL_RISK",
    SMOKING: "VIOLATION",
    VIOLATION: "VIOLATION",
    MISUSE: "MISUSE",
  };

  return map[type] || "MISC";
}
