import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* GA4 */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXX"
          strategy="afterInteractive"
        />
        <Script id="ga-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-XXXXXXX');
          `}
        </Script>

        {/* PostHog */}
        <Script id="posthog-init" strategy="afterInteractive">
          {`
            !function(t,e){var o,n,p,r;e.__SV||(window.posthog=e,e._i=[],e.init=function(i,s,a){ 
            function g(t,e){var o=e.split(".");2==o.length&&(t=t[o[0]],e=o[1]), 
            t[e]=function(){t.push([e].concat(Array.prototype.slice.call(arguments,0)))}} 
            (p=t.createElement("script")).type="text/javascript",p.async=!0, 
            p.src=s.api_host+"/static/array.js",(r=t.getElementsByTagName("script")[0]) 
            .parentNode.insertBefore(p,r);var u=e; 
            for(void 0!==a?u=e[a]=[]:a="posthog",u.people=u.people||[], 
            u.toString=function(t){var e="posthog";return"posthog"!==a&&(e+="."+a), 
            t||(e+=" (stub)"),e},u.people.toString=function(){return u.toString(1)+".people (stub)"}, 
            o="capture identify alias people.set people.set_once people.unset people.increment people.append people.remove people.group people.track".split(" "), 
            n=0;n<o.length;n++)g(u,o[n]);e._i.push([i,s,a])}, 
            e.init("phc_XXXX",{api_host:"https://app.posthog.com"})}(document,window.posthog||[]);
          `}
        </Script>

        {children}
      </body>
    </html>
  );
}
