export const COMPLAINT_TYPES = [
  "PAYMENT_ISSUE",
  "COMMUNICATION_ISSUE",
  "MAINTENANCE_DELAY",
  "PROPERTY_CONDITION",
  "UNPROFESSIONAL_BEHAVIOR",
  "BILLING_INACCURACY",
  "REFUND_PROBLEM",
  "SAFETY_CONCERN",
  "DEPOSIT_DISPUTE",
  "OTHER"
];