export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  SUPPORT_ADMIN: "SUPPORT_ADMIN",
  SUPPORT_AGENT: "SUPPORT_AGENT",
  COMPLIANCE_AGENT: "COMPLIANCE_AGENT",
  CONTENT_MODERATOR: "CONTENT_MODERATOR",
  SALES_AGENT: "SALES_AGENT",

  ORG_OWNER: "ORG_OWNER",
  ORG_STAFF: "ORG_STAFF",

  RENTER: "RENTER",
  UNINITIALIZED: "UNINITIALIZED",
} as const;

export type Role = typeof ROLES[keyof typeof ROLES];
