"use client";

import { useEffect, useState } from "react";
import { notFound } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

export default function PublicRenterReport({ params }: any) {
  const { renterId } = params;

  const [renter, setRenter] = useState<any>(null);
  const [incidents, setIncidents] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [summary, setSummary] = useState<any>(null);

  useEffect(() => {
    async function load() {
      const res = await fetch(`/api/report/full?renterId=${renterId}`);
      const data = await res.json();

      if (!data.success) return notFound();

      setRenter(data.renter);
      setIncidents(data.incidents);
      setSummary(data.summary);
      setLoading(false);
    }

    load();
  }, [renterId]);

  if (loading) return <p className="p-10">Generating renter report...</p>;
  if (!renter) return notFound();

  return (
    <div className="p-10 max-w-4xl mx-auto space-y-10">
      <h1 className="text-3xl font-semibold">Renter Report</h1>
      <p className="text-sm text-muted-foreground">
        Report generated by the RentFAX Verification Network.
      </p>

      {/* Overview */}
      <section className="border rounded-xl p-6 shadow-sm bg-card space-y-3">
        <h2 className="text-2xl font-semibold">Overview</h2>

        <p><strong>Name:</strong> {renter.fullName}</p>
        <p><strong>Verified Identity:</strong> {renter.verified ? "Verified" : "Unverified"}</p>

        <p className="mt-3"><strong>Risk Score:</strong></p>
        <Badge variant={summary.riskScore >= 7 ? "destructive" : "secondary"}>
          {summary.riskScore} / 10
        </Badge>

        <p className="text-sm text-muted-foreground mt-2">
          {summary.riskExplanation}
        </p>
      </section>

      {/* Incident History */}
      <section className="border rounded-xl p-6 shadow-sm space-y-6">
        <h2 className="text-2xl font-semibold">Incident History</h2>

        {incidents.length === 0 && (
          <p className="text-muted-foreground text-sm">No incidents found.</p>
        )}

        {incidents.map((incident) => (
          <div
            key={incident.id}
            className="border bg-muted/40 rounded-xl p-4 shadow-sm"
          >
            <h3 className="text-lg font-semibold">
              Incident #{incident.id}
            </h3>

            <div className="flex gap-2 mt-2">
              {incident.publicSignals.map((sig: any, i: number) => (
                <Badge key={i} variant="outline">{sig}</Badge>
              ))}
            </div>

            <p className="mt-4 text-sm">
              <strong>Summary:</strong> {incident.publicSummary}
            </p>

            <p className="text-xs text-muted-foreground mt-2">
              Filed: {new Date(incident.occurredAt).toLocaleString()}
            </p>

            {/* Public timeline */}
            <h4 className="font-medium mt-4">Timeline (Public)</h4>
            <div className="space-y-2">
              {incident.timeline
                .filter((e: any) => !e.internalOnly)
                .map((e: any) => (
                  <div key={e.eventId} className="border rounded-md p-2 bg-white">
                    <p className="text-sm font-medium">{e.type}</p>
                    <p className="text-sm">{e.description}</p>
                    <p className="text-xs text-muted-foreground">
                      {new Date(e.createdAt).toLocaleString()}
                    </p>
                  </div>
                ))}
            </div>
          </div>
        ))}
      </section>

      {/* Risk Associations */}
      <section className="border rounded-xl p-6 shadow-sm space-y-3">
        <h2 className="text-2xl font-semibold">Associated Drivers</h2>

        {summary.associated.length === 0 ? (
          <p className="text-muted-foreground text-sm">No associated identities.</p>
        ) : (
          <ul className="list-disc ml-6">
            {summary.associated.map((a: any, i: number) => (
              <li key={i} className="text-sm">
                Appears in multiple overlapping incidents (privacy safe)
              </li>
            ))}
          </ul>
        )}
      </section>

      {/* Export */}
      <div className="flex justify-end gap-3">
        <Button onClick={() => window.open(`/api/report/pdf?renterId=${renterId}`, "_blank")}>
          Download Full Report PDF
        </Button>
        <Button variant="secondary">
          Download JSON
        </Button>
      </div>
    </div>
  );
}
