export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  COMPANY_OWNER: "COMPANY_OWNER",
  C_LEVEL: "C_LEVEL",
  DIRECTOR: "DIRECTOR",
  MANAGER: "MANAGER",
  STAFF: "STAFF",
  TEMP_AGENT: "TEMP_AGENT",
};
