export const PERMISSIONS = {
  SEARCH_RENTERS: "SEARCH_RENTERS",
  VIEW_REPORTS: "VIEW_REPORTS",
  SUBMIT_INCIDENTS: "SUBMIT_INCIDENTS",
  REVIEW_INCIDENTS: "REVIEW_INCIDENTS",
  APPROVE_VERIFICATIONS: "APPROVE_VERIFICATIONS",
  MANAGE_TEAM: "MANAGE_TEAM",
  VIEW_BILLING: "VIEW_BILLING",
  MANAGE_BILLING: "MANAGE_BILLING",
  MANAGE_ORG: "MANAGE_ORG",
  VIEW_ALERTS: "VIEW_ALERTS"
};
