import { ROLES } from "./index";
import { PERMISSIONS } from "./permissions";

export const ROLE_TEMPLATES: Record<string, string[]> = {
  [ROLES.COMPANY_OWNER]: [
    PERMISSIONS.SEARCH_RENTERS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.SUBMIT_INCIDENTS,
    PERMISSIONS.REVIEW_INCIDENTS,
    PERMISSIONS.APPROVE_VERIFICATIONS,
    PERMISSIONS.MANAGE_TEAM,
    PERMISSIONS.MANAGE_ORG,
    PERMISSIONS.VIEW_BILLING,
    PERMISSIONS.MANAGE_BILLING,
    PERMISSIONS.VIEW_ALERTS,
  ],

  [ROLES.C_LEVEL]: [
    PERMISSIONS.SEARCH_RENTERS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.REVIEW_INCIDENTS,
    PERMISSIONS.VIEW_BILLING,
    PERMISSIONS.VIEW_ALERTS,
  ],

  [ROLES.DIRECTOR]: [
    PERMISSIONS.SEARCH_RENTERS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.REVIEW_INCIDENTS,
    PERMISSIONS.VIEW_ALERTS,
  ],

  [ROLES.MANAGER]: [
    PERMISSIONS.SEARCH_RENTERS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.SUBMIT_INCIDENTS,
    PERMISSIONS.REVIEW_INCIDENTS,
  ],

  [ROLES.STAFF]: [
    PERMISSIONS.SEARCH_RENTERS,
    PERMISSIONS.SUBMIT_INCIDENTS,
  ],

  [ROLES.TEMP_AGENT]: [
    PERMISSIONS.SUBMIT_INCIDENTS,
  ]
};
