export const GLOBAL_ID_TYPES = {
  PASSPORT: "PASSPORT",
  DRIVER_LICENSE: "DRIVER_LICENSE",
  NATIONAL_ID: "NATIONAL_ID",
  RESIDENCE_PERMIT: "RESIDENCE_PERMIT",
  VISA: "VISA",
  CONSULAR_ID: "CONSULAR_ID",
};
