export function generateLegalSection(renterId) {
  return `
    This report is generated by RentFAX based on data provided by 
    verified landlords, property managers, and authenticated users.

    RentFAX does not alter, edit, or manipulate submitted evidence.
    Renter ${renterId} has the right to dispute any incident.

    This report is compliant with:
    - FCRA guidelines for consumer reports
    - basic state landlord-tenant disclosure rules
    - RentFAX data integrity standards
  `;
}
