name: PR Preview

on:
  pull_request:

jobs:
  deploy-preview:
    name: Deploy PR Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_RENTFAX_REVAMP }}'
          projectId: rentfax-revamp
